### ISSUE TITLE
Question | What is this Project's Goals?

### ISSUE THREAD

**Issue by ghbjklhv** [stallmanifold/rust-i2p#2]
**Question**: What is this projects goals? 

Is it meant to replace [i2p-rs](https://github.com/i2p/i2p-rs) or be a more fully fledged client like [i2pd](https://github.com/PurpleI2P/i2pd)?

**Comment by stallmanifold** [comment]
It was originally meant to be a from scratch implementation of the i2p protocol along the lines of ```i2pd```, but in Rust. This is no longer the case since I am no longer working on it and I have moved on to other things. If you're looking to contribute to the i2p ecosystem I am sure some of the other projects are happy to work with you.
